limits:
  cobweb: 16
  ender_pearl: 0
  golden_apple: 32
  strength_2: 2
  speed_2: 2

cooldowns:
  mace: 5
  trident: 3

netherite:
  allow_crafting: false 
  blocked_items:
    helmet: false
    chestplate: false
    leggings: false
    boots: false
    pickaxe: false
    axe: false
    shovel: false
    hoe: false
