name: SMPCustomization
version: 1.0
main: pl.twojadomena.smp.SMPCustomization
api-version: '1.21'
commands:
  smpconfig:
    description: Zarzadzanie konfiguracja SMP
    permission: smp.admin
  buffs:
    description: Daje efekty Strength II oraz Speed II
